In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [2]:
# x is the input matrix, w is the weight matrix and b is the bias matrix
def neuron(x, w, b):
  return np.dot(x, w) + b

In [3]:
# batch inputs (original 0th layer inputs which is our actual data)
# batches help in generalizing better to the dataset rather than giving a single input each time to fit
# Selecting the correct batch size is the key if the batch size if too large and close to the actual size of data it will overfit to the training data as all the data is exposed at once while keeping batch size small will not fit to the entire data correctly as it will each time try to fit to single data points
# Recommended batch sizes are 16, 32, 64 but depends on size of the data
input = [[1,2,3], [2,3,4], [3,4,5]]
weights1 = [[1,2,3],[2,3,4], [3,4,5]]
bias1 = [1,2,3]
weight2 = [[1,2,3],[2,3,4], [3,4,5]]
bias2 = [1,2,3]
layer1_output = neuron(input, weights1, bias1)
layer2_output = neuron(layer1_output, weight2, bias2)
layer2_output

array([[147, 214, 281],
       [207, 301, 395],
       [267, 388, 509]])

In [4]:

for i in layer1_output:
  i = 1/(1+np.exp(-i))
  print(i)
for i in layer2_output:
  i = 1/(1+np.exp(-i))
  print(i)

[0.99999969 1.         1.        ]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]
[1. 1. 1.]


In [ ]:
class Layer:
  def __init__(self, x, y):
    pass
  def forward(self, x):
    pass
  def backward(self, x):
    pass

